
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
 ssl_certificate: /ssl/fullchain.pem
 ssl_key: /ssl/privkey.pem


cover:
 platform: mqtt
 name: "Motorized Blinds"
 command_topic: "BlindsMCU/blindsCommand"
 set_position_topic: "BlindsMCU/positionCommand"
 position_topic: "BlindsMCU/positionState"
 state_topic: "BlindsMCU/positionState"
 retain: true
 payload_open: "OPEN"
 payload_close: "CLOSE"
 payload_stop: "STOP"
 position_open: 0
 position_closed: 12

api:

sensor:
  platform: mqtt
  name: "Temperature"
  state_topic: "temperature"
  qos: 0
  unit_of_measurement: "ºF"

sensor1:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

sensor 2:
  platform: mqtt
  name: "Humidity"
  state_topic: "humidity"
  qos: 0
  unit_of_measurement: "%"
  
sensor 3:
  platform: mqtt
  name: bedroom gas
  state_topic: "gas"
  qos: 0
  unit_of_measurement: "ppm"
  
switch:
  - platform: mqtt
    name: Lock
    state_topic: "lock"
    command_topic: "lock"
    payload_on: "1"
    payload_off: "0"
